Retrieval evaluation tells us if we're finding the right documents.
RAG/LLM evaluation tells us if the generated answers are actually good enough (context). We use the LLM-as-a-judge approach.

In [1]:
# Load the ground truth data (questions + id).
import pandas as pd
df_question = pd.read_csv("../data/ground-truth-retrieval.csv")
ground_truth = df_question.to_dict(orient="records")

In [2]:
len(ground_truth)

200

In [3]:
ground_truth[0]

{'question': 'What are the warning signs of an abdominal aortic aneurysm?',
 'chunk_id': 'abdominal-aortic-aneurysm-1'}

In [4]:
# fetch the nhs dataset.

import json

with open("../data/nhs-symptom-chunks.json", "r", encoding="utf-8") as f:
    documents = json.load(f)

print(f'{len(documents)=}')       # Number of objects

len(documents)=6855

In [ ]:
# copied from nhs_search_pgdb.ipynb

import psycopg

conn = psycopg.connect(
    'postgresql://user:password@postgres:5432/nhs-patient-assistant'
)
conn.execute("CREATE EXTENSION IF NOT EXISTS vector")

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [7]:
def vec_to_str(vector):
    return '[' + ','.join(str(x) for x in vector) + ']'

In [8]:
def pgvector_search(query, num_results=10):
    query_vector = model.encode(query)
    query_str = vec_to_str(query_vector)

    rows = conn.execute(
        """
        SELECT chunk_id, section, heading, content
        FROM documents
        ORDER BY embedding <=> %s::vector
        LIMIT %s
        """,
        (query_str, num_results)
    ).fetchall()

    return [
        {'chunk_id':r[0], 'section': r[1], 'heading': r[2], 'content': r[3]}
        for r in rows
    ]

In [9]:
def keyword_search(query, num_results=10):

    rows = conn.execute(
        """
        SELECT
            chunk_id,
            section,
            heading,
            content,
            ts_rank(
                search_vector,
                websearch_to_tsquery(
                    'english',
                    replace(%s, ' ', ' OR ')
                )
            ) AS score
        FROM documents
        WHERE search_vector @@ websearch_to_tsquery(
            'english',
            replace(%s, ' ', ' OR ')
        )
        ORDER BY score DESC
        LIMIT %s
        """,
        (query, query, num_results)
    ).fetchall()



    return [
        {   'chunk_id': r[0],
            'section': r[1],
            'heading': r[2],
            'content': r[3]
        }
        for r in rows
    ]

In [10]:
from openai import OpenAI

openai_client = OpenAI()


def llm(prompt, model="gpt-5.4-mini"):
    response = openai_client.responses.create(
        model=model,
        input=prompt
    )

    return response.output_text

In [11]:
def rewrite_query(question):

    prompt = f"""
You are a search query optimizer for an NHS medical document retrieval system.

Rewrite the user's question into a short keyword-based search query
for retrieving relevant NHS medical documents.

Rules:
- Remove conversational phrases such as "I've had", "should I", "do I need", "what should I do".
- Keep the main medical concepts from the user's question.
- Keep symptoms, conditions, body parts, treatments, medications, and risk factors.
- Convert everyday wording into common medical terms where appropriate.
- Keep clinically important qualifiers such as severity, urgency, duration, age group, or risk factors when they help retrieval.
- Remove generic words that do not improve retrieval, such as "medical help", "advice", "information", unless they are essential.
- Do not add diagnoses, symptoms, or treatments that are not mentioned by the user.
- Prefer 3-8 meaningful search terms.
- Optimise for high recall in NHS document retrieval.
- Return only the rewritten search query.


User question:
{question}

Rewritten query:
"""

    return llm(prompt)

In [12]:
def rrf(search_results, k=1, num_results=10): 
    scores = {}
    doc_map = {}

    for results in search_results:
        for rank, doc in enumerate(results):
            key = doc["chunk_id"]
            if key not in scores:
                scores[key] = 0
                doc_map[key] = doc
            scores[key] += 1 / (k + rank + 1)

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return [doc_map[key] for key, _ in ranked[:num_results]]

In [13]:
def hybrid_search(original_query, rewritten_query, num_results=10):

    vector_results = pgvector_search(query=original_query,num_results=num_results)
    keyword_results = keyword_search(query=rewritten_query,num_results=num_results)

    return rrf([keyword_results, vector_results], num_results=num_results)

In [14]:
# we turned a list of dictionaries into one string. 
def build_context(search_results):
    lines = []

    for doc in search_results:
        lines.append(doc["section"])
        lines.append(doc["heading"])        
        lines.append(doc["content"])
        lines.append("")

    return "\n".join(lines).strip()

In [15]:
USER_PROMPT_TEMPLATE = """
Question:
{question}

Context:
{context}
"""

In [16]:
# combine the question with the context into the user prompt:

def build_prompt(query, search_results):
    context = build_context(search_results)
    prompt = USER_PROMPT_TEMPLATE.format(
        question=query,
        context=context
    )
    return prompt.strip()

In [17]:
# Call the LLM

from openai import OpenAI

openai_client = OpenAI()

def llm(prompt, model="gpt-5.4-mini"):
    response = openai_client.responses.create(
        model=model,
        input=[{"role": "user", "content": prompt}]
    )

    return response.output_text

In [27]:
def search(query):
    rewritten_query = rewrite_query(query)
    return hybrid_search(original_query=query, rewritten_query=rewritten_query, num_results=10)

In [29]:
# Put it together

def rag(query, model="gpt-5.4-mini"):
    search_results = search(query)
    prompt = build_prompt(query, search_results)
    answer = llm(prompt, model=model)
    return answer

In [30]:
# LLM-as-a-Judge for RAG
# we will use the LLM to evaluate the relevance of generated answers.

prompt2_template = """
You are an expert evaluator for a RAG system.
Your task is to analyze the relevance of the generated answer to the given question.
Based on the relevance of the generated answer, you will classify it
as 'NON_RELEVANT', 'PARTLY_RELEVANT', or 'RELEVANT'.

Here is the data for evaluation:

Question: {question}
Generated Answer: {answer_llm}

Please analyze the content and context of the generated answer in relation to the question
and provide your evaluation in parsable JSON without using code blocks:

{{
  'Relevance': 'NON_RELEVANT' | 'PARTLY_RELEVANT' | 'RELEVANT',
  'Explanation': '[Provide a brief explanation for your evaluation]'
}}
""".strip()

In [31]:
df_question

,question,chunk_id
0,What are the warning signs of an abdominal aor...,abdominal-aortic-aneurysm-1
1,When should I get urgent medical help for symp...,abdominal-aortic-aneurysm-1
2,What are the symptoms of an abdominal aortic a...,abdominal-aortic-aneurysm-2
3,Am I at higher risk of getting an abdominal ao...,abdominal-aortic-aneurysm-2
4,Could abdominal aortic aneurysm cause pain or ...,abdominal-aortic-aneurysm-3
...,...,...
195,Are there any risk factors or inherited gene c...,acute-lymphoblastic-leukaemia-9
196,If I have Down’s syndrome or another genetic c...,acute-lymphoblastic-leukaemia-10
197,Does acute lymphoblastic leukaemia run in fami...,acute-lymphoblastic-leukaemia-10
198,Could being exposed to very high levels of rad...,acute-lymphoblastic-leukaemia-11
199,Is exposure to radon a risk factor for acute l...,acute-lymphoblastic-leukaemia-11

In [32]:
# Take a sample of ground truth questions, generate answers, and evaluate:

import json
from tqdm.auto import tqdm

df_sample = df_question.sample(n=200, random_state=1) 
sample = df_sample.to_dict(orient="records")

evaluations = []

for record in tqdm(sample):
    question = record["question"]
    answer_llm = rag(question) # full search/ return ans.

    prompt = prompt2_template.format(
        question=question,
        answer_llm=answer_llm
    )

    evaluation = llm(prompt) # evaluate the answer from llm.i.e. is the ans good enough?
    evaluation = json.loads(evaluation)

    evaluations.append((record, answer_llm, evaluation))

  0%|          | 0/200 [00:00<?, ?it/s]

In [33]:
# Analyze the results:

df_eval = pd.DataFrame(evaluations, columns=["record", "answer", "evaluation"]) # adding column labels as evaluations doesn't have headings.

df_eval.head()

,record,answer,evaluation
0,{'question': 'Could being overweight increase ...,Yes. Being overweight or obese can increase yo...,"{'Relevance': 'RELEVANT', 'Explanation': 'The ..."
1,{'question': 'If my abdominal aortic aneurysm ...,If your abdominal aortic aneurysm (AAA) is **5...,"{'Relevance': 'RELEVANT', 'Explanation': 'The ..."
2,{'question': 'How is an abdominal aortic aneur...,An abdominal aortic aneurysm is usually diagno...,"{'Relevance': 'RELEVANT', 'Explanation': 'The ..."
3,{'question': 'When should I stop using heat or...,"For **Achilles tendinopathy**, stop using **he...","{'Relevance': 'RELEVANT', 'Explanation': 'The ..."
4,{'question': 'What symptoms might I notice if ...,"If your blood cells aren’t working properly, t...","{'Relevance': 'RELEVANT', 'Explanation': 'The ..."

In [34]:
df_eval["id"] = df_eval.record.apply(lambda d: d["chunk_id"]) # note: record is a column
df_eval["question"] = df_eval.record.apply(lambda d: d["question"])
df_eval["relevance"] = df_eval.evaluation.apply(lambda d: d["Relevance"]) # evaluation is a column
df_eval["explanation"] = df_eval.evaluation.apply(lambda d: d["Explanation"])

df_eval.relevance.value_counts(normalize=True)

relevance
RELEVANT           0.98
PARTLY_RELEVANT    0.02
Name: proportion, dtype: float64

In [35]:
df_eval.head()

,record,answer,evaluation,id,question,relevance,explanation
0,{'question': 'Could being overweight increase ...,Yes. Being overweight or obese can increase yo...,"{'Relevance': 'RELEVANT', 'Explanation': 'The ...",abdominal-aortic-aneurysm-30,Could being overweight increase my risk of an ...,RELEVANT,The answer directly addresses the question by ...
1,{'question': 'If my abdominal aortic aneurysm ...,If your abdominal aortic aneurysm (AAA) is **5...,"{'Relevance': 'RELEVANT', 'Explanation': 'The ...",abdominal-aortic-aneurysm-21,If my abdominal aortic aneurysm is 5.5cm or la...,RELEVANT,The answer directly addresses the question by ...
2,{'question': 'How is an abdominal aortic aneur...,An abdominal aortic aneurysm is usually diagno...,"{'Relevance': 'RELEVANT', 'Explanation': 'The ...",abdominal-aortic-aneurysm-18,How is an abdominal aortic aneurysm usually di...,RELEVANT,The answer directly addresses how an abdominal...
3,{'question': 'When should I stop using heat or...,"For **Achilles tendinopathy**, stop using **he...","{'Relevance': 'RELEVANT', 'Explanation': 'The ...",achilles-tendinopathy-8,When should I stop using heat or ice on my Ach...,RELEVANT,The answer directly addresses when to stop usi...
4,{'question': 'What symptoms might I notice if ...,"If your blood cells aren’t working properly, t...","{'Relevance': 'RELEVANT', 'Explanation': 'The ...",acute-lymphoblastic-leukaemia-4,What symptoms might I notice if my white blood...,RELEVANT,The answer directly addresses the question by ...

In [36]:
# Save the results:
df_eval.to_csv("../data/rag-eval-gpt-5.4-mini.csv", index=False)

In [37]:
# Comparing models
# You can also use evaluation to compare different LLMs.
# For example, compare gpt-5.4-mini with gpt-4o:

evaluations_gpt4o = []

for record in tqdm(sample):
    question = record["question"]
    answer_llm = rag(question, model="gpt-4o")

    prompt = prompt2_template.format(
        question=question,
        answer_llm=answer_llm
    )

    evaluation = llm(prompt) # llm as a judge.
    evaluation = json.loads(evaluation)

    evaluations_gpt4o.append((record, answer_llm, evaluation))

df_eval = pd.DataFrame(evaluations_gpt4o, columns=["record", "answer", "evaluation"])
df_eval["relevance"] = df_eval.evaluation.apply(lambda d: d["Relevance"])
df_eval.relevance.value_counts(normalize=True)

  0%|          | 0/200 [00:00<?, ?it/s]

relevance
RELEVANT           0.915
PARTLY_RELEVANT    0.085
Name: proportion, dtype: float64

In [38]:
# save the results . model="gpt-4o"
df_eval.to_csv("../data/rag-eval-gpt-4o.csv", index=False)

In [39]:
# This gives you a concrete way to decide if a more expensive model is worth the cost. 
# Typically, the cheaper model gives similar results for most questions.
# we will keep to the cheaper model.